/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallerpoo.conexion.base.de.datos;
import static javafx.application.Platform.exit;
import javax.swing.table.DefaultTableModel;
import tallerpoo.conexion.base.de.datos.BaseDatos;
import tallerpoo.conexion.base.de.datos.entidades.Productos;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */

public class VistaCrearUsuarios extends javax.swing.JFrame {
      BaseDatos bd = new BaseDatos();
      Usuarios user = new Usuarios();
      DefaultTableModel modeloTablaCliente = new DefaultTableModel();
      int aux;

    /**
     * Creates new form VistaCrearProducto
     */
    public VistaCrearUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar ventana
         modeloTablaCliente.addColumn("NOMBRE");
        modeloTablaCliente.addColumn("DNI");
        modeloTablaCliente.addColumn("CEL");
        modeloTablaCliente.addColumn("MAIL");
        modeloTablaCliente.addColumn("ROL");
        modeloTablaCliente.addColumn("ESTADO");
        this.tabla_usuarios_id.setModel(modeloTablaCliente);
        
       user = bd.ConsultarUsuarioTabla(tabla_usuarios_id ,modeloTablaCliente);
       tipoUser_id.removeAllItems();
        tipoUser_id.addItem("Vendedor");
        tipoUser_id.addItem("Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mailCliente_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomCliente_text = new javax.swing.JTextField();
        dniCliente_text = new javax.swing.JTextField();
        telCliente_text = new javax.swing.JTextField();
        celCliente_text = new javax.swing.JTextField();
        tipoUser_id = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_usuarios_id = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btn_desactivar = new javax.swing.JButton();
        btnCrearCliente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre");

        jLabel8.setText("Mail");

        mailCliente_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailCliente_textActionPerformed(evt);
            }
        });

        jLabel4.setText("DNI");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Celular");

        nomCliente_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomCliente_textActionPerformed(evt);
            }
        });

        dniCliente_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniCliente_textActionPerformed(evt);
            }
        });

        telCliente_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telCliente_textActionPerformed(evt);
            }
        });

        tipoUser_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUser_idActionPerformed(evt);
            }
        });

        jLabel3.setText("ROL");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dniCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(telCliente_text, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(celCliente_text, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(tipoUser_id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoUser_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailCliente_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios");

        tabla_usuarios_id.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "cel", "mail", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_usuarios_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_usuarios_idMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_usuarios_id);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btn_desactivar.setText("Desactivar");
        btn_desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desactivarActionPerformed(evt);
            }
        });

        btnCrearCliente.setText("CREAR USUARIO");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnAtras.setText("<-atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnCrearCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCrearCliente)
                    .addComponent(btn_desactivar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        

        String tipoUsuer = tipoUser_id.getSelectedItem().toString();

        if(tipoUsuer.equals("Admin")){
        user.id_Rol = 5;
        }else if (tipoUsuer.equals("Vendedor")){
        user.id_Rol = 6;
        }else{
         JOptionPane.showMessageDialog(null, "Selecciona Rol");
         return;
        }
         System.out.println(user.id_Rol);
        
        user.nombre = nomCliente_text.getText();
        user.dni = dniCliente_text.getText();
        user.mail = mailCliente_text.getText();
        user.tel = telCliente_text.getText();
        user.cel = celCliente_text.getText();
        //validar que no traiga campos vacios antes de insertar a la base de datos
        if (user.nombre.equals("") || user.dni.equals("") || user.mail.equals("") || user.cel.equals("") || user.tel.equals("") /*|| user.direccion.equals("")*/ ) {
            JOptionPane.showMessageDialog(null, "llena todos los espacios");
        } else {
             bd.insertarUsuarios(user);
           // dispose();//para cerrarla al ir a otra
        }
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    private void nomCliente_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomCliente_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomCliente_textActionPerformed

    private void dniCliente_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniCliente_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniCliente_textActionPerformed

    private void telCliente_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telCliente_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telCliente_textActionPerformed

    private void mailCliente_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailCliente_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailCliente_textActionPerformed

    private void tabla_usuarios_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_usuarios_idMouseClicked
        // TODO add your handling code here:
        int rowIndex = tabla_usuarios_id.getSelectedRow();
        String dni = tabla_usuarios_id.getValueAt(rowIndex, 1).toString();
        user = bd.ConsultarUsuariosID(dni);
        nomCliente_text.setText(user.nombre);
        dniCliente_text.setText(user.dni);
        celCliente_text.setText(user.cel);
        mailCliente_text.setText(user.mail);
        telCliente_text.setText(user.tel);
        
        //tipoUser_id.removeAllItems();
        if(user.id_Rol == 5){
           tipoUser_id.removeAllItems();
           tipoUser_id.addItem("Admin");
           tipoUser_id.addItem("Vendedor");
        }else if(user.id_Rol == 6){
            tipoUser_id.removeAllItems();
           tipoUser_id.addItem("Vendedor");
            tipoUser_id.addItem("Admin");
        }else{
            tipoUser_id.removeAllItems();
            tipoUser_id.addItem("Super-Admin");
        }
          
        if(user.estado == 0){
            btn_desactivar.setText("ACTIVAR");
            aux = 1;
        }else if (user.estado == 1){
            btn_desactivar.setText("DESACTIVAR");
            aux = 0;
        }
    }//GEN-LAST:event_tabla_usuarios_idMouseClicked

    private void tipoUser_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUser_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUser_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        user.nombre = nomCliente_text.getText();
        user.dni = dniCliente_text.getText();
        user.mail = mailCliente_text.getText();
        user.tel = telCliente_text.getText();
        user.cel = celCliente_text.getText();
        String tipoUsuer = tipoUser_id.getSelectedItem().toString();
        if(tipoUsuer.equals("Admin")){
            user.id_Rol = 5;
        }else if(tipoUsuer.equals("Vendedor")){
            user.id_Rol = 6;
        }else{
            JOptionPane.showMessageDialog(null, "Super-Admin no se puede actualizar");
          return;
        }
                

        bd.ActualizarUsuario(user);
        DefaultTableModel model = (DefaultTableModel) tabla_usuarios_id.getModel();
        model.setRowCount(0);
        bd.ConsultarUsuarioTabla(tabla_usuarios_id, modeloTablaCliente);

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btn_desactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desactivarActionPerformed
        // TODO add your handling code here:    
        bd.DesactivarUsuario(user, aux);
        DefaultTableModel model = (DefaultTableModel) tabla_usuarios_id.getModel();
        model.setRowCount(0);
        bd.ConsultarUsuarioTabla(tabla_usuarios_id, modeloTablaCliente);
    }//GEN-LAST:event_btn_desactivarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        dispose();//para cerrarla al ir a otra 
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrearUsuarios().setVisible(true);
            }
        });
    }
    
    public void Limpiar(){
    
        nomCliente_text.setText("");
        dniCliente_text.setText("");
        celCliente_text.setText("");
        mailCliente_text.setText("");
        telCliente_text.setText("");
        tipoUser_id.removeAllItems();
        tipoUser_id.addItem("Vendedor");
        tipoUser_id.addItem("Admin");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btn_desactivar;
    private javax.swing.JTextField celCliente_text;
    private javax.swing.JTextField dniCliente_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mailCliente_text;
    private javax.swing.JTextField nomCliente_text;
    private javax.swing.JTable tabla_usuarios_id;
    private javax.swing.JTextField telCliente_text;
    private javax.swing.JComboBox<String> tipoUser_id;
    // End of variables declaration//GEN-END:variables
}
